name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - run: ./scripts/setup.sh
      - run: npm run lint
      - run: npm run build
      - run: npm test
        if: ${{ hashFiles('**/*.test.*', '**/*.spec.*') != '' }}

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel deploy
        run: |
          curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}
